---
title: "Data codebook"
date: "Last updated `r Sys.Date()`"
output: html_document
---

To cite these data:
[add data paper reference here]

Here we present codebook information for the demographic variables including summary statistics and distributions for each. Codebook information for the 5,636 vocabulary items has been omitted as this would compromise their validity for subsequent use. Contact the lead author of the reference above for access to this information.

```{r setup, include=FALSE}
knit_by_pkgdown <- !is.null(knitr::opts_chunk$get("fig.retina"))
knitr::opts_chunk$set(
  warning = FALSE, # hide warnings during codebook generation
  message = FALSE, # hide messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # TRUE is usually better for debugging
  echo = FALSE  # hide R code
)
ggplot2::theme_set(ggplot2::theme_bw())

```

```{r packages}
library(here)
library(tidyverse)
library(codebook)
```


```{r load data}
codebook_data <- read.csv(here("data/TDA_data_scored.csv"))
```

```{r remove_items}
codebook_data = select(codebook_data, -starts_with("q_"), -PID)
```


```{r}
codebook_data = codebook_data %>%
  mutate(
    StartDate = str_remove(StartDate, "T"),
    StartDate = str_remove(StartDate, "Z"),
    StartDate = as.Date(StartDate)) %>%
  mutate(english = factor(english, 
                          levels = c(
                            "Very well (fluent/native)",
                            "Well",
                            "Not well",
                            "Not at all (Need translation)")),
    growup = factor(growup, 
                          levels = c(
                            "United States of America",
                            "Outside of the US")),
    live = factor(live,
                  levels = c(
                    "Yes",
                    "No")),
    state = factor(state, levels = c(state.name[1:8], "District of Columbia", state.name[9:50])),
    sex = factor(sex, 
                 levels = c(
                   "Male",
                   "Female",
                   "Other",
                   "Prefer not to say")),
    edu = factor(edu,
                 levels = c(
                   "Less than 12 years", 
                   "High school grad/GED",
                   "Currently in college/university",
                   "Some college/university, but did not graduate",
                   "Associate degree (2 yr)",
                   "College/university degree (4 yr)",
                   "Currently in grad/professional school",
                   "Grad/professional degree")),
    ethnic = factor(ethnic, 
                    levels = c(
                      "American Indian/Alaskan Native",
                      "Asian",
                      "Black",
                      "Hispanic",
                      "White",
                      "Mixed (two or more)",
                      "Other")),
    hhinc = factor(hhinc, 
                   levels = c(
                     "< 20K",
                     "20K-40K",
                     "40K-60K",
                     "60K-80K",
                     "80K-100K",
                     "100K-120K",
                     "120K-150K",
                     "150K-200K",
                     "200K-250K",
                     "250K-350K",
                     "350K-500K",
                     "> 500K",
                     "Prefer not to say")))
```



```{r variable labels}
attributes(codebook_data$source)$label <- "Data collection platform."
attributes(codebook_data$StartDate)$label <- "Date and time started survey."
attributes(codebook_data$duration)$label <- "Time in seconds."
attributes(codebook_data$english)$label <- "How well do you speak English?"
attributes(codebook_data$growup)$label <- "Where did you grow up?"
attributes(codebook_data$live)$label <- "Do you currently live in one of the 50 states of the USA or the District of Columbia?"
attributes(codebook_data$state)$label <- "Please select the state where you currently live (or spend the most time)."
attributes(codebook_data$age)$label <- "Age (in years)."
attributes(codebook_data$sex)$label <- "Biological sex at birth."
attributes(codebook_data$edu)$label <- "Level of education."
attributes(codebook_data$ethnic)$label <- "Racial or ethnic background."
attributes(codebook_data$hhinc)$label <- "Household income."
attributes(codebook_data$included)$label <- "Row included in calculation of item and TDA difficulty."
attributes(codebook_data$prop_correct)$label <- "Proportion of correct responses."
```

```{r metadata}
metadata(codebook_data)$name <- "Trait descriptive adjectives (scored)"
#metadata(codebook_data)$description <- ""
#metadata(codebook_data)$identifier <- ""
metadata(codebook_data)$creator <- "David Condon, Joshua Coughlin, Sara Weston"
#metadata(codebook_data)$citation <- ""
#metadata(codebook_data)$url <- ""
#metadata(codebook_data)$datePublished <- ""
metadata(codebook_data)$temporalCoverage <- "Spring 2020 and Spring 2021" 
metadata(codebook_data)$spatialCoverage <- "Online" 

```

```{r cb}
codebook(codebook_data, metadata_table = knit_by_pkgdown, metadata_json = TRUE)
```